name: Build Android Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Set up Android SDK
        uses: reactivecircus/android-sdk-action@v2
        with:
          api-levels: '35'
          build-tools: '35.0.0'

      - name: Build with Gradle
        run: ./gradlew assembleDebug
